#ifndef TH1INFO_H
#define TH1INFO_H

#include <string>
#include "enumList.h"

const string Hits_Row_Title1 = "Hits in Row ";
const string Hits_Row_Title2 = "Ideal Hits in Row ";
const string Hits_Row_xTitle = "Column";
const string Hits_Row_yTitle = "Hits";
const int    Hits_Row_Bin = 53;
const double Hits_Row_Min = 0;
const double Hits_Row_Max = 53;

struct TH1Info_{
	string 	Name;
	string 	Title;
	string 	xTitle;
	string 	yTitle;
	string 	Unit;
	int 	Bin;
	double 	Min;
	double 	Max;
};

struct TH1Info_ TH1Info[TH1_Size_] = {
	{ "ROCnumber", 	"ROC Number", 	"Number", 	"Hits", 	"", 	8, 0, 8},
	{ "Row", 	"Row Hits", 	"Row", 		"Hits", 	"", 	82, -1, 81},
	{ "Column", 	"Column Hits", 	"Column", 	"Hits", 	"", 	54, -1, 53},

	{ "Hits_Row_0",		(Hits_Row_Title1+"0"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_0_ideal",	(Hits_Row_Title2+"0"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_1",		(Hits_Row_Title1+"1"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_1_ideal",	(Hits_Row_Title2+"1"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_2",		(Hits_Row_Title1+"2"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_2_ideal",	(Hits_Row_Title2+"2"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_3",		(Hits_Row_Title1+"3"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_3_ideal",	(Hits_Row_Title2+"3"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_4",		(Hits_Row_Title1+"4"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_4_ideal",	(Hits_Row_Title2+"4"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_5",		(Hits_Row_Title1+"5"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_5_ideal",	(Hits_Row_Title2+"5"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_6",		(Hits_Row_Title1+"6"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_6_ideal",	(Hits_Row_Title2+"6"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_7",		(Hits_Row_Title1+"7"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_7_ideal",	(Hits_Row_Title2+"7"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_8",		(Hits_Row_Title1+"8"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_8_ideal",	(Hits_Row_Title2+"8"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_9",		(Hits_Row_Title1+"9"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_9_ideal",	(Hits_Row_Title2+"9"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_10",	(Hits_Row_Title1+"10"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_10_ideal",	(Hits_Row_Title2+"10"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_11",	(Hits_Row_Title1+"11"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_11_ideal",	(Hits_Row_Title2+"11"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_12",	(Hits_Row_Title1+"12"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_12_ideal",	(Hits_Row_Title2+"12"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_13",	(Hits_Row_Title1+"13"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_13_ideal",	(Hits_Row_Title2+"13"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_14",	(Hits_Row_Title1+"14"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_14_ideal",	(Hits_Row_Title2+"14"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_15",	(Hits_Row_Title1+"15"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_15_ideal",	(Hits_Row_Title2+"15"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_16",	(Hits_Row_Title1+"16"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_16_ideal",	(Hits_Row_Title2+"16"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_17",	(Hits_Row_Title1+"17"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_17_ideal",	(Hits_Row_Title2+"17"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_18",	(Hits_Row_Title1+"18"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_18_ideal",	(Hits_Row_Title2+"18"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_19",	(Hits_Row_Title1+"19"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_19_ideal",	(Hits_Row_Title2+"19"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_20",	(Hits_Row_Title1+"20"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_20_ideal",	(Hits_Row_Title2+"20"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_21",	(Hits_Row_Title1+"21"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_21_ideal",	(Hits_Row_Title2+"21"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_22",	(Hits_Row_Title1+"22"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_22_ideal",	(Hits_Row_Title2+"22"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_23",	(Hits_Row_Title1+"23"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_23_ideal",	(Hits_Row_Title2+"23"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_24",	(Hits_Row_Title1+"24"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_24_ideal",	(Hits_Row_Title2+"24"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_25",	(Hits_Row_Title1+"25"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_25_ideal",	(Hits_Row_Title2+"25"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_26",	(Hits_Row_Title1+"26"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_26_ideal",	(Hits_Row_Title2+"26"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_27",	(Hits_Row_Title1+"27"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_27_ideal",	(Hits_Row_Title2+"27"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_28",	(Hits_Row_Title1+"28"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_28_ideal",	(Hits_Row_Title2+"28"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_29",	(Hits_Row_Title1+"29"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_29_ideal",	(Hits_Row_Title2+"29"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_30",	(Hits_Row_Title1+"30"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_30_ideal",	(Hits_Row_Title2+"30"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_31",	(Hits_Row_Title1+"31"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_31_ideal",	(Hits_Row_Title2+"31"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_32",	(Hits_Row_Title1+"32"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_32_ideal",	(Hits_Row_Title2+"32"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_33",	(Hits_Row_Title1+"33"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_33_ideal",	(Hits_Row_Title2+"33"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_34",	(Hits_Row_Title1+"34"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_34_ideal",	(Hits_Row_Title2+"34"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_35",	(Hits_Row_Title1+"35"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_35_ideal",	(Hits_Row_Title2+"35"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_36",	(Hits_Row_Title1+"36"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_36_ideal",	(Hits_Row_Title2+"36"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_37",	(Hits_Row_Title1+"37"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_37_ideal",	(Hits_Row_Title2+"37"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_38",	(Hits_Row_Title1+"38"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_38_ideal",	(Hits_Row_Title2+"38"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_39",	(Hits_Row_Title1+"39"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_39_ideal",	(Hits_Row_Title2+"39"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_40",	(Hits_Row_Title1+"40"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_40_ideal",	(Hits_Row_Title2+"40"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_41",	(Hits_Row_Title1+"41"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_41_ideal",	(Hits_Row_Title2+"41"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_42",	(Hits_Row_Title1+"42"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_42_ideal",	(Hits_Row_Title2+"42"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_43",	(Hits_Row_Title1+"43"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_43_ideal",	(Hits_Row_Title2+"43"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_44",	(Hits_Row_Title1+"44"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_44_ideal",	(Hits_Row_Title2+"44"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_45",	(Hits_Row_Title1+"45"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_45_ideal",	(Hits_Row_Title2+"45"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_46",	(Hits_Row_Title1+"46"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_46_ideal",	(Hits_Row_Title2+"46"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_47",	(Hits_Row_Title1+"47"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_47_ideal",	(Hits_Row_Title2+"47"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_48",	(Hits_Row_Title1+"48"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_48_ideal",	(Hits_Row_Title2+"48"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_49",	(Hits_Row_Title1+"49"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_49_ideal",	(Hits_Row_Title2+"49"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_50",	(Hits_Row_Title1+"50"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_50_ideal",	(Hits_Row_Title2+"50"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_51",	(Hits_Row_Title1+"51"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_51_ideal",	(Hits_Row_Title2+"51"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_52",	(Hits_Row_Title1+"52"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_52_ideal",	(Hits_Row_Title2+"52"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_53",	(Hits_Row_Title1+"53"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_53_ideal",	(Hits_Row_Title2+"53"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_54",	(Hits_Row_Title1+"54"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_54_ideal",	(Hits_Row_Title2+"54"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_55",	(Hits_Row_Title1+"55"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_55_ideal",	(Hits_Row_Title2+"55"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_56",	(Hits_Row_Title1+"56"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_56_ideal",	(Hits_Row_Title2+"56"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_57",	(Hits_Row_Title1+"57"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_57_ideal",	(Hits_Row_Title2+"57"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_58",	(Hits_Row_Title1+"58"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_58_ideal",	(Hits_Row_Title2+"58"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_59",	(Hits_Row_Title1+"59"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_59_ideal",	(Hits_Row_Title2+"59"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_60",	(Hits_Row_Title1+"60"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_60_ideal",	(Hits_Row_Title2+"60"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_61",	(Hits_Row_Title1+"61"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_61_ideal",	(Hits_Row_Title2+"61"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_62",	(Hits_Row_Title1+"62"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_62_ideal",	(Hits_Row_Title2+"62"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_63",	(Hits_Row_Title1+"63"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_63_ideal",	(Hits_Row_Title2+"63"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_64",	(Hits_Row_Title1+"64"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_64_ideal",	(Hits_Row_Title2+"64"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_65",	(Hits_Row_Title1+"65"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_65_ideal",	(Hits_Row_Title2+"65"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_66",	(Hits_Row_Title1+"66"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_66_ideal",	(Hits_Row_Title2+"66"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_67",	(Hits_Row_Title1+"67"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_67_ideal",	(Hits_Row_Title2+"67"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_68",	(Hits_Row_Title1+"68"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_68_ideal",	(Hits_Row_Title2+"68"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_69",	(Hits_Row_Title1+"69"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_69_ideal",	(Hits_Row_Title2+"69"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_70",	(Hits_Row_Title1+"70"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_70_ideal",	(Hits_Row_Title2+"70"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_71",	(Hits_Row_Title1+"71"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_71_ideal",	(Hits_Row_Title2+"71"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_72",	(Hits_Row_Title1+"72"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_72_ideal",	(Hits_Row_Title2+"72"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_73",	(Hits_Row_Title1+"73"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_73_ideal",	(Hits_Row_Title2+"73"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_74",	(Hits_Row_Title1+"74"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_74_ideal",	(Hits_Row_Title2+"74"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_75",	(Hits_Row_Title1+"75"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_75_ideal",	(Hits_Row_Title2+"75"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_76",	(Hits_Row_Title1+"76"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_76_ideal",	(Hits_Row_Title2+"76"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_77",	(Hits_Row_Title1+"77"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_77_ideal",	(Hits_Row_Title2+"77"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_78",	(Hits_Row_Title1+"78"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_78_ideal",	(Hits_Row_Title2+"78"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_79",	(Hits_Row_Title1+"79"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_79_ideal",	(Hits_Row_Title2+"79"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_80",	(Hits_Row_Title1+"80"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_80_ideal",	(Hits_Row_Title2+"80"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},	
};




#endif  
