#ifndef TH1INFO_H
#define TH1INFO_H

#include <string>
#include "enumList.h"

const string Hits_Row_Title1 = "Hits in Row ";
const string Hits_Row_Title2 = "Ideal Hits in Row ";
const string Hits_Row_xTitle = "Column";
const string Hits_Row_yTitle = "Hits";
const string Ratio_Row_Title  = "Ratio of Hits in Row ";
const string Ratio_Row_yTitle = "Ratio";
const int    Hits_Row_Bin = 53;
const double Hits_Row_Min = 0;
const double Hits_Row_Max = 53;

const string Hits_2Col_Title1 = "Hits in Column";
const string Hits_2Col_Title2 = "Ideal Hits in Column";
const string Hits_2Col_xTitle = "Row";
const string Hits_2Col_yTitle = "Hits";
const string Ratio_2Col_Title  = "Ratio of Hits in Column ";
const string Ratio_2Col_yTitle = "Ratio";
const int    Hits_2Col_Bin = 161;
const double Hits_2Col_Min = 0;
const double Hits_2Col_Max = 161;

struct TH1Info_{
	string 	Name;
	string 	Title;
	string 	xTitle;
	string 	yTitle;
	string 	Unit;
	int 	Bin;
	double 	Min;
	double 	Max;
};

struct TH1Info_ TH1Info[TH1_Size_] = {
	{ "ROCnumber", 	"ROC Number", 	"Number", 	"Hits", 	"", 	8, 0, 8},
	{ "Row", 	"Row Hits", 	"Row", 		"Hits", 	"", 	82, -1, 81},
	{ "Column", 	"Column Hits", 	"Column", 	"Hits", 	"", 	54, -1, 53},

	{ "Hits_2Col_0.1",		(Hits_2Col_Title1+"[0,1]"), Hits_2Col_xTitle, Hits_2Col_yTitle,		"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_0.1_ideal",	(Hits_2Col_Title2+"[0,1]"), Hits_2Col_xTitle, Hits_2Col_yTitle,		"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Ratio_2Col_0.1",		(Ratio_2Col_Title+"[0,1]"), Hits_2Col_xTitle, Ratio_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_2.3",		(Hits_2Col_Title1+"[2,3]"), Hits_2Col_xTitle, Hits_2Col_yTitle,		"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_2.3_ideal",	(Hits_2Col_Title2+"[2,3]"), Hits_2Col_xTitle, Hits_2Col_yTitle,		"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Ratio_2Col_2.3",		(Ratio_2Col_Title+"[2,3]"), Hits_2Col_xTitle, Ratio_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_4.5",		(Hits_2Col_Title1+"[4,5]"), Hits_2Col_xTitle, Hits_2Col_yTitle,		"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_4.5_ideal",	(Hits_2Col_Title2+"[4,5]"), Hits_2Col_xTitle, Hits_2Col_yTitle,		"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Ratio_2Col_4.5",		(Ratio_2Col_Title+"[4,5]"), Hits_2Col_xTitle, Ratio_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_6.7",		(Hits_2Col_Title1+"[6,7]"), Hits_2Col_xTitle, Hits_2Col_yTitle,		"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_6.7_ideal",	(Hits_2Col_Title2+"[6,7]"), Hits_2Col_xTitle, Hits_2Col_yTitle,		"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Ratio_2Col_6.7",		(Ratio_2Col_Title+"[6,7]"), Hits_2Col_xTitle, Ratio_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_8.9",		(Hits_2Col_Title1+"[8,9]"), Hits_2Col_xTitle, Hits_2Col_yTitle,		"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_8.9_ideal",	(Hits_2Col_Title2+"[8,9]"), Hits_2Col_xTitle, Hits_2Col_yTitle,		"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Ratio_2Col_8.9",		(Ratio_2Col_Title+"[8,9]"), Hits_2Col_xTitle, Ratio_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_10.11",		(Hits_2Col_Title1+"[10,11]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_10.11_ideal",	(Hits_2Col_Title2+"[10,11]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Ratio_2Col_10.11",		(Ratio_2Col_Title+"[10,11]"), Hits_2Col_xTitle, Ratio_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_12.13",		(Hits_2Col_Title1+"[12,13]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_12.13_ideal",	(Hits_2Col_Title2+"[12,13]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Ratio_2Col_12.13",		(Ratio_2Col_Title+"[12,13]"), Hits_2Col_xTitle, Ratio_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_14.15",		(Hits_2Col_Title1+"[14,15]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_14.15_ideal",	(Hits_2Col_Title2+"[14,15]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Ratio_2Col_14.15",		(Ratio_2Col_Title+"[14,15]"), Hits_2Col_xTitle, Ratio_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_16.17",		(Hits_2Col_Title1+"[16,17]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_16.17_ideal",	(Hits_2Col_Title2+"[16,17]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Ratio_2Col_16.17",		(Ratio_2Col_Title+"[16,17]"), Hits_2Col_xTitle, Ratio_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_18.19",		(Hits_2Col_Title1+"[18,19]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_18.19_ideal",	(Hits_2Col_Title2+"[18,19]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Ratio_2Col_18.19",		(Ratio_2Col_Title+"[18,19]"), Hits_2Col_xTitle, Ratio_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_20.21",		(Hits_2Col_Title1+"[20,21]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_20.21_ideal",	(Hits_2Col_Title2+"[20,21]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Ratio_2Col_20.21",		(Ratio_2Col_Title+"[20,21]"), Hits_2Col_xTitle, Ratio_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_22.23",		(Hits_2Col_Title1+"[22,23]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_22.23_ideal",	(Hits_2Col_Title2+"[22,23]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Ratio_2Col_22.23",		(Ratio_2Col_Title+"[22,23]"), Hits_2Col_xTitle, Ratio_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_24.25",		(Hits_2Col_Title1+"[24,25]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_24.25_ideal",	(Hits_2Col_Title2+"[24,25]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Ratio_2Col_24.25",		(Ratio_2Col_Title+"[24,25]"), Hits_2Col_xTitle, Ratio_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_26.27",		(Hits_2Col_Title1+"[26,27]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_26.27_ideal",	(Hits_2Col_Title2+"[26,27]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Ratio_2Col_26.27",		(Ratio_2Col_Title+"[26,27]"), Hits_2Col_xTitle, Ratio_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_28.29",		(Hits_2Col_Title1+"[28,29]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_28.29_ideal",	(Hits_2Col_Title2+"[28,29]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Ratio_2Col_28.29",		(Ratio_2Col_Title+"[28,29]"), Hits_2Col_xTitle, Ratio_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_30.31",		(Hits_2Col_Title1+"[30,31]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_30.31_ideal",	(Hits_2Col_Title2+"[30,31]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Ratio_2Col_30.31",		(Ratio_2Col_Title+"[30,31]"), Hits_2Col_xTitle, Ratio_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_32.33",		(Hits_2Col_Title1+"[32,33]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_32.33_ideal",	(Hits_2Col_Title2+"[32,33]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Ratio_2Col_32.33",		(Ratio_2Col_Title+"[32,33]"), Hits_2Col_xTitle, Ratio_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_34.35",		(Hits_2Col_Title1+"[34,35]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_34.35_ideal",	(Hits_2Col_Title2+"[34,35]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Ratio_2Col_34.35",		(Ratio_2Col_Title+"[34,35]"), Hits_2Col_xTitle, Ratio_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_36.37",		(Hits_2Col_Title1+"[36,37]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_36.37_ideal",	(Hits_2Col_Title2+"[36,37]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Ratio_2Col_36.37",		(Ratio_2Col_Title+"[36,37]"), Hits_2Col_xTitle, Ratio_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_38.39",		(Hits_2Col_Title1+"[38,39]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_38.39_ideal",	(Hits_2Col_Title2+"[38,39]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Ratio_2Col_38.39",		(Ratio_2Col_Title+"[38,39]"), Hits_2Col_xTitle, Ratio_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_40.41",		(Hits_2Col_Title1+"[40,41]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_40.41_ideal",	(Hits_2Col_Title2+"[40,41]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Ratio_2Col_40.41",		(Ratio_2Col_Title+"[40,41]"), Hits_2Col_xTitle, Ratio_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_42.43",		(Hits_2Col_Title1+"[42,43]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_42.43_ideal",	(Hits_2Col_Title2+"[42,43]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Ratio_2Col_42.43",		(Ratio_2Col_Title+"[42,43]"), Hits_2Col_xTitle, Ratio_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_44.45",		(Hits_2Col_Title1+"[44,45]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_44.45_ideal",	(Hits_2Col_Title2+"[44,45]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Ratio_2Col_44.45",		(Ratio_2Col_Title+"[44,45]"), Hits_2Col_xTitle, Ratio_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_46.47",		(Hits_2Col_Title1+"[46,47]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_46.47_ideal",	(Hits_2Col_Title2+"[46,47]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Ratio_2Col_46.47",		(Ratio_2Col_Title+"[46,47]"), Hits_2Col_xTitle, Ratio_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_48.49",		(Hits_2Col_Title1+"[48,49]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_48.49_ideal",	(Hits_2Col_Title2+"[48,49]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Ratio_2Col_48.49",		(Ratio_2Col_Title+"[48,49]"), Hits_2Col_xTitle, Ratio_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_50.51",		(Hits_2Col_Title1+"[50,51]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Hits_2Col_50.51_ideal",	(Hits_2Col_Title2+"[50,51]"), Hits_2Col_xTitle, Hits_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},
	{ "Ratio_2Col_50.51",		(Ratio_2Col_Title+"[50,51]"), Hits_2Col_xTitle, Ratio_2Col_yTitle,	"",	Hits_2Col_Bin, Hits_2Col_Min, Hits_2Col_Max},

	{ "Hits_Row_0",		(Hits_Row_Title1+"0"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_0_ideal",	(Hits_Row_Title2+"0"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_0",	(Ratio_Row_Title+"0"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_1",		(Hits_Row_Title1+"1"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_1_ideal",	(Hits_Row_Title2+"1"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_1",	(Ratio_Row_Title+"1"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_2",		(Hits_Row_Title1+"2"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_2_ideal",	(Hits_Row_Title2+"2"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_2",	(Ratio_Row_Title+"2"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_3",		(Hits_Row_Title1+"3"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_3_ideal",	(Hits_Row_Title2+"3"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_3",	(Ratio_Row_Title+"3"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_4",		(Hits_Row_Title1+"4"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_4_ideal",	(Hits_Row_Title2+"4"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_4",	(Ratio_Row_Title+"4"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_5",		(Hits_Row_Title1+"5"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_5_ideal",	(Hits_Row_Title2+"5"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_5",	(Ratio_Row_Title+"5"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_6",		(Hits_Row_Title1+"6"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_6_ideal",	(Hits_Row_Title2+"6"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_6",	(Ratio_Row_Title+"6"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_7",		(Hits_Row_Title1+"7"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_7_ideal",	(Hits_Row_Title2+"7"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_7",	(Ratio_Row_Title+"7"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_8",		(Hits_Row_Title1+"8"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_8_ideal",	(Hits_Row_Title2+"8"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_8",	(Ratio_Row_Title+"8"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_9",		(Hits_Row_Title1+"9"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_9_ideal",	(Hits_Row_Title2+"9"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_9",	(Ratio_Row_Title+"9"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_10",	(Hits_Row_Title1+"10"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_10_ideal",	(Hits_Row_Title2+"10"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_10",	(Ratio_Row_Title+"10"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_11",	(Hits_Row_Title1+"11"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_11_ideal",	(Hits_Row_Title2+"11"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_11",	(Ratio_Row_Title+"11"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_12",	(Hits_Row_Title1+"12"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_12_ideal",	(Hits_Row_Title2+"12"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_12",	(Ratio_Row_Title+"12"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_13",	(Hits_Row_Title1+"13"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_13_ideal",	(Hits_Row_Title2+"13"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_13",	(Ratio_Row_Title+"13"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_14",	(Hits_Row_Title1+"14"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_14_ideal",	(Hits_Row_Title2+"14"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_14",	(Ratio_Row_Title+"14"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_15",	(Hits_Row_Title1+"15"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_15_ideal",	(Hits_Row_Title2+"15"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_15",	(Ratio_Row_Title+"15"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_16",	(Hits_Row_Title1+"16"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_16_ideal",	(Hits_Row_Title2+"16"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_16",	(Ratio_Row_Title+"16"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_17",	(Hits_Row_Title1+"17"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_17_ideal",	(Hits_Row_Title2+"17"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_17",	(Ratio_Row_Title+"17"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_18",	(Hits_Row_Title1+"18"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_18_ideal",	(Hits_Row_Title2+"18"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_18",	(Ratio_Row_Title+"18"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_19",	(Hits_Row_Title1+"19"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_19_ideal",	(Hits_Row_Title2+"19"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_19",	(Ratio_Row_Title+"19"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_20",	(Hits_Row_Title1+"20"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_20_ideal",	(Hits_Row_Title2+"20"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_20",	(Ratio_Row_Title+"20"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_21",	(Hits_Row_Title1+"21"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_21_ideal",	(Hits_Row_Title2+"21"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_21",	(Ratio_Row_Title+"21"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_22",	(Hits_Row_Title1+"22"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_22_ideal",	(Hits_Row_Title2+"22"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_22",	(Ratio_Row_Title+"22"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_23",	(Hits_Row_Title1+"23"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_23_ideal",	(Hits_Row_Title2+"23"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_23",	(Ratio_Row_Title+"23"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_24",	(Hits_Row_Title1+"24"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_24_ideal",	(Hits_Row_Title2+"24"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_24",	(Ratio_Row_Title+"24"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_25",	(Hits_Row_Title1+"25"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_25_ideal",	(Hits_Row_Title2+"25"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_25",	(Ratio_Row_Title+"25"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_26",	(Hits_Row_Title1+"26"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_26_ideal",	(Hits_Row_Title2+"26"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_26",	(Ratio_Row_Title+"26"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_27",	(Hits_Row_Title1+"27"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_27_ideal",	(Hits_Row_Title2+"27"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_27",	(Ratio_Row_Title+"27"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_28",	(Hits_Row_Title1+"28"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_28_ideal",	(Hits_Row_Title2+"28"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_28",	(Ratio_Row_Title+"28"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_29",	(Hits_Row_Title1+"29"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_29_ideal",	(Hits_Row_Title2+"29"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_29",	(Ratio_Row_Title+"29"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_30",	(Hits_Row_Title1+"30"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_30_ideal",	(Hits_Row_Title2+"30"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_30",	(Ratio_Row_Title+"30"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_31",	(Hits_Row_Title1+"31"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_31_ideal",	(Hits_Row_Title2+"31"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_31",	(Ratio_Row_Title+"31"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_32",	(Hits_Row_Title1+"32"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_32_ideal",	(Hits_Row_Title2+"32"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_32",	(Ratio_Row_Title+"32"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_33",	(Hits_Row_Title1+"33"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_33_ideal",	(Hits_Row_Title2+"33"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_33",	(Ratio_Row_Title+"33"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_34",	(Hits_Row_Title1+"34"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_34_ideal",	(Hits_Row_Title2+"34"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_34",	(Ratio_Row_Title+"34"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_35",	(Hits_Row_Title1+"35"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_35_ideal",	(Hits_Row_Title2+"35"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_35",	(Ratio_Row_Title+"35"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_36",	(Hits_Row_Title1+"36"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_36_ideal",	(Hits_Row_Title2+"36"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_36",	(Ratio_Row_Title+"36"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_37",	(Hits_Row_Title1+"37"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_37_ideal",	(Hits_Row_Title2+"37"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_37",	(Ratio_Row_Title+"37"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_38",	(Hits_Row_Title1+"38"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_38_ideal",	(Hits_Row_Title2+"38"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_38",	(Ratio_Row_Title+"38"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_39",	(Hits_Row_Title1+"39"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_39_ideal",	(Hits_Row_Title2+"39"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_39",	(Ratio_Row_Title+"39"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_40",	(Hits_Row_Title1+"40"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_40_ideal",	(Hits_Row_Title2+"40"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_40",	(Ratio_Row_Title+"40"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_41",	(Hits_Row_Title1+"41"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_41_ideal",	(Hits_Row_Title2+"41"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_41",	(Ratio_Row_Title+"41"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_42",	(Hits_Row_Title1+"42"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_42_ideal",	(Hits_Row_Title2+"42"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_42",	(Ratio_Row_Title+"42"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_43",	(Hits_Row_Title1+"43"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_43_ideal",	(Hits_Row_Title2+"43"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_43",	(Ratio_Row_Title+"43"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_44",	(Hits_Row_Title1+"44"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_44_ideal",	(Hits_Row_Title2+"44"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_44",	(Ratio_Row_Title+"44"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_45",	(Hits_Row_Title1+"45"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_45_ideal",	(Hits_Row_Title2+"45"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_45",	(Ratio_Row_Title+"45"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_46",	(Hits_Row_Title1+"46"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_46_ideal",	(Hits_Row_Title2+"46"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_46",	(Ratio_Row_Title+"46"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_47",	(Hits_Row_Title1+"47"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_47_ideal",	(Hits_Row_Title2+"47"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_47",	(Ratio_Row_Title+"47"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_48",	(Hits_Row_Title1+"48"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_48_ideal",	(Hits_Row_Title2+"48"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_48",	(Ratio_Row_Title+"48"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_49",	(Hits_Row_Title1+"49"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_49_ideal",	(Hits_Row_Title2+"49"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_49",	(Ratio_Row_Title+"49"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_50",	(Hits_Row_Title1+"50"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_50_ideal",	(Hits_Row_Title2+"50"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_50",	(Ratio_Row_Title+"50"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_51",	(Hits_Row_Title1+"51"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_51_ideal",	(Hits_Row_Title2+"51"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_51",	(Ratio_Row_Title+"51"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_52",	(Hits_Row_Title1+"52"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_52_ideal",	(Hits_Row_Title2+"52"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_52",	(Ratio_Row_Title+"52"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_53",	(Hits_Row_Title1+"53"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_53_ideal",	(Hits_Row_Title2+"53"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_53",	(Ratio_Row_Title+"53"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_54",	(Hits_Row_Title1+"54"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_54_ideal",	(Hits_Row_Title2+"54"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_54",	(Ratio_Row_Title+"54"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_55",	(Hits_Row_Title1+"55"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_55_ideal",	(Hits_Row_Title2+"55"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_55",	(Ratio_Row_Title+"55"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_56",	(Hits_Row_Title1+"56"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_56_ideal",	(Hits_Row_Title2+"56"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_56",	(Ratio_Row_Title+"56"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_57",	(Hits_Row_Title1+"57"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_57_ideal",	(Hits_Row_Title2+"57"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_57",	(Ratio_Row_Title+"57"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_58",	(Hits_Row_Title1+"58"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_58_ideal",	(Hits_Row_Title2+"58"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_58",	(Ratio_Row_Title+"58"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_59",	(Hits_Row_Title1+"59"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_59_ideal",	(Hits_Row_Title2+"59"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_59",	(Ratio_Row_Title+"59"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_60",	(Hits_Row_Title1+"60"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_60_ideal",	(Hits_Row_Title2+"60"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_60",	(Ratio_Row_Title+"60"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_61",	(Hits_Row_Title1+"61"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_61_ideal",	(Hits_Row_Title2+"61"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_61",	(Ratio_Row_Title+"61"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_62",	(Hits_Row_Title1+"62"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_62_ideal",	(Hits_Row_Title2+"62"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_62",	(Ratio_Row_Title+"62"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_63",	(Hits_Row_Title1+"63"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_63_ideal",	(Hits_Row_Title2+"63"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_63",	(Ratio_Row_Title+"63"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_64",	(Hits_Row_Title1+"64"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_64_ideal",	(Hits_Row_Title2+"64"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_64",	(Ratio_Row_Title+"64"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_65",	(Hits_Row_Title1+"65"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_65_ideal",	(Hits_Row_Title2+"65"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_65",	(Ratio_Row_Title+"65"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_66",	(Hits_Row_Title1+"66"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_66_ideal",	(Hits_Row_Title2+"66"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_66",	(Ratio_Row_Title+"66"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_67",	(Hits_Row_Title1+"67"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_67_ideal",	(Hits_Row_Title2+"67"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_67",	(Ratio_Row_Title+"67"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_68",	(Hits_Row_Title1+"68"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_68_ideal",	(Hits_Row_Title2+"68"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_68",	(Ratio_Row_Title+"68"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_69",	(Hits_Row_Title1+"69"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_69_ideal",	(Hits_Row_Title2+"69"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_69",	(Ratio_Row_Title+"69"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_70",	(Hits_Row_Title1+"70"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_70_ideal",	(Hits_Row_Title2+"70"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_70",	(Ratio_Row_Title+"70"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_71",	(Hits_Row_Title1+"71"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_71_ideal",	(Hits_Row_Title2+"71"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_71",	(Ratio_Row_Title+"71"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_72",	(Hits_Row_Title1+"72"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_72_ideal",	(Hits_Row_Title2+"72"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_72",	(Ratio_Row_Title+"72"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_73",	(Hits_Row_Title1+"73"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_73_ideal",	(Hits_Row_Title2+"73"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_73",	(Ratio_Row_Title+"73"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_74",	(Hits_Row_Title1+"74"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_74_ideal",	(Hits_Row_Title2+"74"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_74",	(Ratio_Row_Title+"74"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_75",	(Hits_Row_Title1+"75"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_75_ideal",	(Hits_Row_Title2+"75"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_75",	(Ratio_Row_Title+"75"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_76",	(Hits_Row_Title1+"76"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_76_ideal",	(Hits_Row_Title2+"76"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_76",	(Ratio_Row_Title+"76"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_77",	(Hits_Row_Title1+"77"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_77_ideal",	(Hits_Row_Title2+"77"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_77",	(Ratio_Row_Title+"77"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_78",	(Hits_Row_Title1+"78"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_78_ideal",	(Hits_Row_Title2+"78"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_78",	(Ratio_Row_Title+"78"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_79",	(Hits_Row_Title1+"79"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_79_ideal",	(Hits_Row_Title2+"79"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_79",	(Ratio_Row_Title+"79"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_80",	(Hits_Row_Title1+"80"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Hits_Row_80_ideal",	(Hits_Row_Title2+"80"), Hits_Row_xTitle, Hits_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
	{ "Ratio_Row_80",	(Ratio_Row_Title+"80"), Hits_Row_xTitle, Ratio_Row_yTitle,	"",	Hits_Row_Bin, Hits_Row_Min, Hits_Row_Max},
};




#endif  
